### ISSUE TITLE
How to describe collections?

### ISSUE THREAD

**Issue by georgr** [developmentseed/rio-stac#27]
Hi,

this is not really an issue more a question, but I do not know where to ask it properly: 

I´m currently try to setup a proof-of-concept stack for stac (😁):

- creating COG´s -> **rio cogeo**
- create stac items -> **rio stac**
- create stac collection metadata from the described items-> ???
- load and store stac metadata -> **pgstac**
- provide stac api backed by pgstac -> **stac-fastapi**
- visualize stac items -> **titiler**

The tooling is awesome, I got everything up and running, so thanks for your support so far 👍 

The only thing I can´t find a answer in the workflow is how to create a stac collection from a bunch of stac items created with **rio stac** to load it in pgstac. 
Currently I´m writing it manually and I´m thinking about scripting it with pystac. Is this the right way or am I missing something?

Thanks for helping out!

**Comment by vincentsarago** [comment]
@georgr we have a WIP project over https://github.com/developmentseed/eoAPI that covers most of it. 

> - creating COG´s -> rio cogeo

This is a really hard subject because there are as much COG configuration than Input data. 

> - create stac items -> rio stac

https://github.com/developmentseed/stac-fastapi-rio-stac is an extension to stac-fastapi (but its not up to date)
